# Working with numpy

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4])
array1

array([1, 2, 3, 4])

In [3]:
# This i just tried out myself

array2 = np.array(["Subhayan", "Dimpu", 1, 2, 3])
array2

array(['Subhayan', 'Dimpu', '1', '2', '3'], dtype='<U8')

In [4]:
zeros = np.zeros((3, 4))  # 3 rows and 4 columns array
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
ones = np.ones((3, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
eyes = np.eye(3)
eyes

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
eyes = np.eye(5)
eyes

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
eyes.shape

(5, 5)

In [9]:
array_of_evens = np.arange(2, 20, 2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
array_of_floats = np.arange(0, 2, 0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [11]:
to_dim = np.array([(1, 2, 3), (4, 5, 6)])
to_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
to_dim.shape

(2, 3)

In [13]:
to_dim.ndim

2

In [14]:
# Quite common to first create the array and then later reshape it

check = np.arange(10)
check

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
check.reshape(2, 5)  # Since we want to reshape it to 2 rows and 5 columns it needs 10 elements. Otherwise this might fail

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
new = check.reshape(5, 2)
new

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [36]:
# Here we are using the above array to create a new array having same dimensions but having only 1

new_array = np.ones_like(new)
new_array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [37]:
assert new_array.shape == new.shape

In [3]:
new = np.arange(24).reshape(2, 3, 4)  # contains 2 arrays of size 3 x 4
new

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
arr1 = np.array([10, 10, 10])
arr2 = np.array([5, 5, 5])

In [5]:
arr1 + arr2

array([15, 15, 15])

In [6]:
arr1 - arr2

array([5, 5, 5])

In [7]:
arr1 * arr2

array([50, 50, 50])

In [8]:
arr1 / arr2

array([2., 2., 2.])

In [9]:
arr1 < 35

array([ True,  True,  True])

In [10]:
if np.all(arr1 < 35):
    print("All are true")
else:
    print("Some are true")

All are true


In [11]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [12]:
A

array([[1, 1],
       [0, 1]])

In [13]:
B

array([[2, 0],
       [3, 4]])

In [15]:
A * B  # (Element wise multiplication)

array([[2, 0],
       [0, 4]])

In [16]:
# To do matrix multiplication we use the dot function in numpy

A.dot(B)

array([[5, 4],
       [3, 4]])

In [18]:
# Same result as above

np.dot(A, B)  # Number of columns in the first matrix should be equal to number of rows in second matrix B

array([[5, 4],
       [3, 4]])

In [19]:
ages = np.array([12, 35, 90, 45])


In [20]:
np.sum(ages)

182

In [21]:
new = np.arange(12).reshape(3, 4)
new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
new.sum(axis=0)  # result has same number of columns , and the sum of every column is done to display the result

array([12, 15, 18, 21])

In [25]:
new.sum(axis=1)  # Sum across all rows

array([ 6, 22, 38])

In [27]:
print(new)
new.min(axis=1)  # Find the minimum value across each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 4, 8])

In [28]:
a = np.arange(11) ** 2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [31]:
# This is a row major flattening by default, So first the elements of a row then column etc.

arr = np.array([[1, 2, 3], [4, 5, 6]])  # Flatten the array to basically get every element of the n dimensional array
for a in arr.flatten():
    print(a)

1
2
3
4
5
6


In [32]:
# To use column wise flattening

arr = np.array([[1, 2, 3], [4, 5, 6]])  # Flatten the array to basically get every element of the n dimensional array
for a in arr.flatten(order='F'):
    print(a)

1
4
2
5
3
6


In [17]:
new = np.arange(12).reshape(3, 4)
new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
for i in np.nditer(new):  # Iterate over the array in row major form
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [37]:
for i in np.nditer(new, order='F'):  # Iterate over the array in column major form
    print(i)
    
# Flatten gives me a new array while nditer just helps me iterate

0
4
8
1
5
9
2
6
10
3
7
11


In [40]:
print(new)
for i in np.nditer(new, flags=['external_loop']):
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [43]:
print(new)
print("....")
for i in np.nditer(new, order='F', flags=['external_loop']):
    print(i)
    
# using nditer we can just iterate through it , we cannot assign

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
....
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [18]:
print(new)
print("....")
for x in np.nditer(new, op_flags=['readwrite']):
    x[...] = x * x

print(new)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
....
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [19]:
data = np.array([(1, 2, 3), (4, 5, 6)])

In [20]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
data.shape

(2, 3)

In [22]:
data.ravel()  # This is also a function which can be used to flatten an array just like flatten

array([1, 2, 3, 4, 5, 6])

In [23]:
data.flatten()

array([1, 2, 3, 4, 5, 6])

In [25]:
np.ravel(data)  # This works but does not work in the same way for flatten

array([1, 2, 3, 4, 5, 6])

In [26]:
data2 = np.array([(10, 20, 30), (40, 50, 60)])

In [29]:
np.ravel([data, data2])  # So ravel can also work on a list of nd arrays

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30, 40, 50, 60])

In [31]:
data.T  # Transpose the array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
data.shape

(2, 3)

In [34]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
check = np.arange(20).reshape(4, 5)

In [38]:
check

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
check.reshape(2, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [40]:
new = np.arange(12)

In [41]:
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
new.reshape(-1, 3)  # Negative index in the first argument basically means that we don't know how many rows 
# The final reshaped array should contain as long as there are 3 columns

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
data = np.arange(9)

In [45]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
np.split(data, 3)  # Split the resulting array into 3 arrays of size 3

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [48]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
np.split(data, [3, 4])  # Split the array at position 3 and again at position 4

[array([0, 1, 2]), array([3]), array([4, 5, 6, 7, 8])]

In [52]:
new = np.array([(1, 2, 3, 4), (4, 5, 6, 7)])
new

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [54]:
p1, p2 = np.hsplit(new, 2)  # Split the array vertically

In [55]:
p1

array([[1, 2],
       [4, 5]])

In [56]:
p2

array([[3, 4],
       [6, 7]])

In [57]:
# There is also a vsplit function to do the exact opposite split of the above array

In [60]:
!conda install -y scipy

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.4
  latest version: 4.8.5

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/subhayanbhattacharya/miniconda3/envs/notebooks

  added / updated specs:
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-3.0.1          |       h93005f0_2         426 KB
    scipy-1.5.0                |   py38hbab996c_0        13.3 MB
    ------------------------------------------------------------
                                           Total:        13.7 MB

The following NEW packages will be INSTALLED:

  libgfortran        pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  scipy              pkgs/main/osx-64::scipy-1.5.0-py38hbab996c_0



scipy-1.5.0          | 13.3 MB   | ##############################

In [61]:
import scipy

In [63]:
!conda install -y pillow

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.4
  latest version: 4.8.5

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/subhayanbhattacharya/miniconda3/envs/notebooks

  added / updated specs:
    - pillow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jpeg-9b                    |       he5867d9_2         201 KB
    lcms2-2.11                 |       h92f6f08_0         278 KB
    libtiff-4.1.0              |       hcb84e12_1         405 KB
    lz4-c-1.9.2                |       hb1e8313_1         142 KB
    olefile-0.46               |             py_0          33 KB
    pillow-7.2.0               |   py38ha54b6ba_0         583 KB
    zstd-1.4.5                 |       h41d2c2f_0         442 KB
    --------------------------------------------------